apiVersion: v1
kind: Service
metadata:
  name: raft-svc
spec:
  clusterIP: None
  selector:
    app: raft
  ports:
  - name: rpc
    port: 29280
    protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raft
spec:
  serviceName: "raft-svc"
  replicas: 3
  selector:
    matchLabels:
      app: raft
  template:
    metadata:
      labels:
        app: raft
    spec:
      containers:
      - name: raft-node
        image: localhost:5001/nodoraft:latest
        imagePullPolicy: IfNotPresent
        # command: ["/bin/sh", "-c"]
        # args:
        # - "./nodoRaft \"$MY_ID\" raft-0.raft-svc:29280 raft-1.raft-svc:29280 raft-2.raft-svc:29280"
        args:
          - "$(MY_ID)"
          - "raft-0.raft-svc:29280"
          - "raft-1.raft-svc:29280"
          - "raft-2.raft-svc:29280"
        env:
        - name: MY_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 29280
          name: rpc
        readinessProbe:
          tcpSocket:
            port: rpc
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: rpc
          initialDelaySeconds: 30
          periodSeconds: 10
      # opcional: intentar distribuir pods en distintos nodos (si el cluster tiene varios workers)
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: raft
            topologyKey: "kubernetes.io/hostname"
