# ==================================
# ServiceAccount para permitir a boot ver Pods
# ==================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boot-sa

---
# ==================================
# Role que da permisos de listar y ver Pods
# ==================================
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: boot-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
# ==================================
# RoleBinding → asigna permisos a boot-sa
# ==================================
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boot-rb
subjects:
- kind: ServiceAccount
  name: boot-sa
roleRef:
  kind: Role
  name: boot-role
  apiGroup: rbac.authorization.k8s.io

---
# ==================================
# JOB — Espera a Raft y luego activa timers vía RPC
# ==================================
apiVersion: batch/v1
kind: Job
metadata:
  name: raft-boot
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: boot-sa
      containers:
      - name: boot
        image: localhost:5001/boot:latest
        imagePullPolicy: Always
